name       : eid-mw
version    : 4.2.5
release    : 1
source     :
    - https://github.com/Fedict/eid-mw/archive/v4.2.5.tar.gz : d2c46a65026790485f39db0b6d9b66a65b1d19061f3682a0b6da2e2b0c54bc81
homepage   : https://eid.belgium.be
license    : LGPL-3.0
component  : security
summary    : Belgium electronic identity card viewer, PKCS#11 module and Firefox plugin
description: |
    The eid-viewer application allows the user to read out any information from
    a Belgian electronic identity card. Both identity information and information
    about the stored cryptographic keys can be read in a user-friendly manner,
    and can easily be printed out or stored for later reviewal.

    The application verifies the signature of the identity information,
    checks whether it was signed by a government-issued key, and optionally
    checks the certificate against the government's Trust Service.

    The eID Middleware provides the libraries, a PKCS#11 module and a Firefox
    plugin to use Belgian eID (electronic identity) card in order to access
    websites and/or sign documents.
patterns   :
    - firefox:
        - /usr/lib64/firefox/
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(p11-kit-1)
setup      : |
    %reconfigure --disable-static --with-mozext=%libdir%/firefox/browser/extensions
build      : |
    %make
install    : |
    %make_install
    rm -frv $installdir/usr/share/locale/en@*quot
