name       : eid-mw
version    : 4.4.27
release    : 21
source     :
    - https://github.com/Fedict/eid-mw/archive/v4.4.27.tar.gz : 68d2b1a1792a386d546fb3cd86c992f749dd32b5749ae5c5b309a6beef5cfeb1
homepage   : https://eid.belgium.be
license    : LGPL-3.0-or-later
component  :
    - security
    - firefox : security
summary    :
    - Belgium electronic identity card viewer (eID Viewer) and PKCS#11 module
    - firefox : Belgian electronic identity card (eID) add-on for Mozilla Firefox
description: |
    The eid-viewer application allows the user to read out any information from a Belgian electronic identity card. Both identity information and information about the stored cryptographic keys can be read in a user-friendly manner, and can easily be printed out or stored for later reviewal.

    The application verifies the signature of the identity information, checks whether it was signed by a government-issued key, and optionally checks the certificate against the government's Trust Service.

    The eID Middleware provides the libraries, a PKCS#11 module and a Firefox plugin to use Belgian eID (electronic identity) card in order to access websites and/or sign documents.
patterns   :
    - firefox :
        - /usr/lib/mozilla/
        - /usr/share/mozilla/
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libpcsclite)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(p11-kit-1)
rundeps    :
    - firefox : eid-mw
    - pcsc-lite
setup      : |
    %reconfigure --disable-static --enable-webextension
build      : |
    %make
install    : |
    %make_install
    rm -frv $installdir/usr/share/locale/en@*quot
check      : |
    %make check
